package gradingTools.comp524f20.assignment1.testcases.socialDistance.utility;

import java.lang.reflect.Method;
import java.util.Arrays;

import grader.basics.execution.BasicProjectExecution;
import grader.basics.execution.ResultWithOutput;
import grader.basics.junit.JUnitTestsEnvironment;
import grader.basics.junit.NotAutomatableException;
import grader.basics.junit.TestCaseResult;
import grader.basics.project.NotGradableException;
import grader.basics.project.Project;
import grader.basics.testcase.PassFailJUnitTestCase;
import gradingTools.comp524f20.assignment1.testcases.socialDistance.requiredClasses.SocialDistanceUtilityProvided;
import util.annotations.MaxValue;
@MaxValue(5)
public class PrintSafeDistancesAndDurationsTest extends PassFailJUnitTestCase {
	public static final int TIME_OUT_MSECS = 300; // secs
	
	protected final String methodName = "printSafeDistancesAndDurations";

	protected static Class[] parameterTypes= {Integer.TYPE};
	protected static Object[][] arguments= {
			{9}, //<small 
			{0},
			{5},
			{10},
			
			{11}, //small to medium
			{29},
			{17},
			{30},
			
			{31}, //medium to large
			{49},
			{41},
			{50},
			
			{51}, //>large
			{70},
			{101},
			{Integer.MAX_VALUE}
			
	};
	
	protected static String[][] results= {
			{"{6,30}","{13,120}"},
			{"{6,30}","{13,120}"},
			{"{6,30}","{13,120}"},
			{"{6,30}","{13,120}"},
			
			{"{13,30}","{27,120}","{6,15}"},
			{"{13,30}","{27,120}","{6,15}"},
			{"{13,30}","{27,120}","{6,15}"},
			{"{13,30}","{27,120}","{6,15}"},
			
			
			{"{27,30}","{13,15}"},
			{"{27,30}","{13,15}"},
			{"{27,30}","{13,15}"},
			{"{27,30}","{13,15}"},
			
			{},
			{},
			{},
			{}
	};
	protected String [][] getCorrectSubstrings(){
		return results;
	}
	
	protected boolean isPassing=false;
	public boolean isPassing() {
		return isPassing;
	}
	
	protected Object[][] getArguments(){
		return arguments;
	}

	public PrintSafeDistancesAndDurationsTest() {
	}
	
	protected Class[] getParameterTypes() {
		return parameterTypes;
	}
	
	protected  String methodName() {
		return methodName;
	}
	
	@Override
	public TestCaseResult test(Project project, boolean autoGrade) throws NotAutomatableException,
			NotGradableException {
		try {
			SocialDistanceUtilityProvided aSocialDistanceUilityProvided = (SocialDistanceUtilityProvided) JUnitTestsEnvironment.getAndPossiblyRunGradableJUnitTest(SocialDistanceUtilityProvided.class);
			Class aUtilityClass = aSocialDistanceUilityProvided.getRequiredClass();
			
//			SocialDistanceClassRegistry aClassRegistry = aClassRegistryProvided.getTimingOutClassRegistryProxy();  
		    if (aUtilityClass == null) {
		    	return fail ("No utility class");
		    }
		    Class[] aParameterTypes = getParameterTypes();
		    Method aMethod = aUtilityClass.getMethod(methodName(), aParameterTypes);
		    Object[][] anArguments = getArguments();
		    
		    int aNumSuccesses=0;
		    String [][] correctDistancesAndDurrations=getCorrectSubstrings();
		    OUTER:
		    for(int i =0; i<anArguments.length;i++) {
		    	ResultWithOutput aResultWithOutput = BasicProjectExecution.timedInteractiveInvoke(aUtilityClass, aMethod, anArguments[i], TIME_OUT_MSECS);
		    	String anOutput = aResultWithOutput.getOutput().replaceAll("I\\*\\*\\*.*\n", "");
		    	if (anOutput == null || anOutput.isEmpty() ) {
			    	System.out.println("No output for arguments "+Arrays.toString(anArguments[i]));
			    	continue;
		    	}
		    
		    	
		    	if(!anOutput.replaceAll("\\{\\d+,\\d+\\}", "p").matches("\\d+,\\[[p,]*\\]\n*")){
		    	//if(!anOutput.matches("\\d+,\\[(?:\\{\\d+,\\d+\\}*\\]\n*")){
	
		    		System.out.println("Output for arguments "+Arrays.toString(anArguments[i])+" did not match regex: \"\\d+,[(?:\\{\\d+,\\d+\\})*]\"");
		    		continue;
		    	}
		    	
		    	int outputPairs=0;
		    	for(char search:anOutput.toCharArray())
		    		outputPairs=search=='{'?outputPairs+1:outputPairs;
		    	
		    	if(outputPairs!=correctDistancesAndDurrations[i].length) {
		    		System.out.println("Number of distance durration pairs in output for arguments "+Arrays.toString(anArguments[i])+" did not match expected number: "+correctDistancesAndDurrations[i].length);
		    		continue;
		    	}
		    	
		    	if(correctDistancesAndDurrations[i].length!=0) {
		    		for(int j=0;j<correctDistancesAndDurrations[i].length;j++) {
		    			if(!anOutput.contains(correctDistancesAndDurrations[i][j])) {
		    				System.out.println("Pattern "+correctDistancesAndDurrations[i][j]+" missing from output generated by "+Arrays.toString(anArguments[i]));
		    				continue OUTER;
		    			}
		    		}
		    	}
		    	aNumSuccesses++;
		    }
		    
		   
		    double aPercentage = ((double) aNumSuccesses)/anArguments.length;
		    isPassing=aPercentage==1;
		    return aPercentage == 1?pass():partialPass(aPercentage, aNumSuccesses + " tests passed out of " + anArguments.length);  

		} catch ( Throwable e) {
			System.err.println(e);
			throw new NotGradableException("caused by:" + e.toString());
		}
	}
}
